export const wilayaUrlToApi = {
  'alger': 'Alger',
  'adrar': 'Adrar',
  'ain-defla': 'Aïn Defla',
  'ain-temouchent': 'Aïn Témouchent',
  'annaba': 'Annaba',
  'batna': 'Batna',
  'bechar': 'Béchar',
  'bejaia': 'Béjaïa',
  'beni-abbes': 'Béni Abbès',
  'biskra': 'Biskra',
  'blida': 'Blida',
  'bordj-badji-mokhtar': 'Bordj Badji Mokhtar',
  'bordj-bou-arreridj': 'Bordj Bou Arréridj',
  'bouira': 'Bouira',
  'boumerdes': 'Boumerdès',
  'chlef': 'Chlef',
  'constantine': 'Constantine',
  'djelfa': 'Djelfa',
  'djanet': 'Djanet',
  'el-bayadh': 'El Bayadh',
  'el-mghair': 'El MGhair',
  'el-meniaa': 'El Meniaa',
  'el-oued': 'El Oued',
  'el-tarf': 'El Tarf',
  'ghardaia': 'Ghardaïa',
  'guelma': 'Guelma',
  'illizi': 'Illizi',
  'in-guezzam': 'In Guezzam',
  'in-salah': 'In Salah',
  'jijel': 'Jijel',
  'khenchela': 'Khenchela',
  'laghouat': 'Laghouat',
  'mascara': 'Mascara',
  'medea': 'Médéa',
  'mila': 'Mila',
  'mostaganem': 'Mostaganem',
  'msila': 'MSila',
  'naama': 'Naâma',
  'oran': 'Oran',
  'ouargla': 'Ouargla',
  'ouled-djellal': 'Ouled Djellal',
  'oum-el-bouaghi': 'Oum El Bouaghi',
  'relizane': 'Relizane',
  'saida': 'Saïda',
  'setif': 'Sétif',
  'sidi-bel-abbes': 'Sidi Bel Abbès',
  'skikda': 'Skikda',
  'souk-ahras': 'Souk Ahras',
  'tamanrasset': 'Tamanrasset',
  'tebessa': 'Tébessa',
  'tiaret': 'Tiaret',
  'timimoun': 'Timimoun',
  'tindouf': 'Tindouf',
  'tipaza': 'Tipaza',
  'tissemsilt': 'Tissemsilt',
  'tizi-ouzou': 'Tizi Ouzou',
  'tlemcen': 'Tlemcen',
  'touggourt': 'Touggourt'
};

export const getApiWilayaName = (urlName) => {
  const normalized = urlName.toLowerCase();
  return wilayaUrlToApi[normalized] || urlName.charAt(0).toUpperCase() + urlName.slice(1);
};

export const wilayaApiToUrl = Object.fromEntries(
  Object.entries(wilayaUrlToApi).map(([url, api]) => [api.toLowerCase(), url])
);
