# Generated by Django 5.2 on 2025-04-15 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_wilaya_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wilaya",
            name="photo",
            field=models.ImageField(
                default="default_wilaya_photo.jpg",
                upload_to="wilaya_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
