# Generated by Django 5.2 on 2025-04-15 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_wilaya_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WilayaPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wilaya_name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="wilaya_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "listings_wilaya_photos",
            },
        ),
    ]
