# Generated by Django 5.2 on 2025-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_wilayaphotos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wilaya",
            name="photo",
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("gasoline", "Gasoline"),
                    ("diesel", "Diesel"),
                    ("electric", "Electric"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
