# Generated by Django 5.2 on 2025-04-16 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_alter_wilayaphotos_wilaya_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="house",
            name="currency",
        ),
    ]
