# Generated by Django 5.2 on 2025-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_remove_car_currency_remove_house_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("rented", "Rented"),
                    ("disabled", "Disabled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("rented", "Rented"),
                    ("disabled", "Disabled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
