# Generated by Django 5.2 on 2025-04-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0012_car_status_house_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("waiting for confirmation", "Waiting for confirmation"),
                    ("rented", "Rented"),
                    ("disabled", "Disabled"),
                ],
                default="available",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("waiting for confirmation", "Waiting for confirmation"),
                    ("rented", "Rented"),
                    ("disabled", "Disabled"),
                ],
                default="available",
                max_length=25,
            ),
        ),
    ]
