# Generated by Django 5.2 on 2025-04-19 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0014_alter_car_status_alter_house_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="house",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="house",
            name="is_furnished",
        ),
    ]
