# Generated by Django 5.2 on 2025-04-20 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_auto_fix"),
        ("listings", "0015_remove_car_is_active_remove_house_is_active_and_more"),
    ]

    operations = []
