# Generated by Django 5.2 on 2025-04-20 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0016_merge_20250420_0622"),
        ("listings", "XXXX_merge"),
    ]

    operations = []
