# Generated by Django 5.2 on 2025-04-20 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0017_merge_0016_merge_20250420_0622_XXXX_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="manufacturing_date",
        ),
    ]
