# Generated by Django 5.2 on 2025-05-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_car_manufacturing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wilaya_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.wilaya')),
            ],
        ),
    ]
