# Generated by Django 5.2 on 2025-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_car_created_at_alter_car_user_alter_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
