# Generated by Django 5.2 on 2025-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_car_la_wilaya_remove_car_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='exact_location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='house',
            name='gps_location',
            field=models.URLField(blank=True, help_text='Google Maps link to the property location', max_length=500, null=True),
        ),
    ]
