# Generated by Django 5.2 on 2025-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_rename_exact_location_house_city_house_gps_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='available', max_length=20),
        ),
    ]
