# Generated by Django 5.2 on 2025-05-10 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_car_status_alter_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms, must be at least 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
