# Generated by Django 5.2 on 2025-05-29 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'house')},
        ),
        migrations.AddField(
            model_name='rating',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_car_ratings', to='listings.car'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_house_ratings', to='listings.house'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'car'), ('user', 'house')},
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('car__isnull', True), ('house__isnull', False)), models.Q(('car__isnull', False), ('house__isnull', True)), _connector='OR'), name='rating_house_xor_car'),
        ),
    ]
