# Generated by Django 5.2 on 2025-04-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_temporaryuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryUser',
        ),
    ]
