# Generated by Django 5.2 on 2025-04-18 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resANDtran", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartransaction",
            options={},
        ),
        migrations.AlterModelOptions(
            name="housetransaction",
            options={},
        ),
        migrations.AddField(
            model_name="cartransaction",
            name="confirmation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartransaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartransaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartransaction",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="housetransaction",
            name="confirmation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="housetransaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="housetransaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="housetransaction",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="housetransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cartransaction",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("edhahabiya", "Edhahabiya")],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cartransaction",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="housetransaction",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="housetransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("edhahabiya", "Edhahabiya")],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="housetransaction",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
