# Generated by Django 5.2 on 2025-04-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resANDtran", "0002_alter_cartransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartransaction",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="resANDtran.carreservation",
            ),
        ),
    ]
