# Generated by Django 5.2 on 2025-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resANDtran", "0003_cartransaction_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="available",
                max_length=24,
            ),
        ),
    ]
