# Generated by Django 5.2 on 2025-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resANDtran", "0004_alter_reservation_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DhahabiyaPayment",
            new_name="MastercardPayment",
        ),
        migrations.RenameField(
            model_name="cartransaction",
            old_name="dhahabiya_payment",
            new_name="mastercard_payment",
        ),
        migrations.RenameField(
            model_name="housetransaction",
            old_name="dhahabiya_payment",
            new_name="mastercard_payment",
        ),
        migrations.AlterField(
            model_name="cartransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("mastercard", "Mastercard")],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="housetransaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("mastercard", "Mastercard")],
                default="cash",
                max_length=50,
            ),
        ),
    ]
