# Generated by Django 5.2 on 2025-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastercardpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('rented', 'Rented'), ('disabled', 'Disabled')], default='pending', max_length=50),
        ),
    ]
