# Generated by Django 5.2 on 2025-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_carreservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housereservation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='housereservation',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='housereservation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='housereservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='carreservation',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastercardpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
