# Generated by Django 5.2 on 2025-05-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_housereservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housereservation',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mastercard', 'Mastercard')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
