# Generated by Django 5.2 on 2025-05-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_housereservation_payment_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housereservation',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='housereservation',
            name='payment_reference',
        ),
    ]
