# Generated by Django 5.2 on 2025-05-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_housereservation_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housereservation',
            options={},
        ),
        migrations.RenameField(
            model_name='housereservation',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='housereservation',
            name='created_at',
        ),
    ]
