# Generated by Django 5.2 on 2025-05-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_carreservation_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreservation',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='carreservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carreservation',
            name='payment_details',
        ),
    ]
