# Generated by Django 5.2 on 2025-05-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0024_rename_exact_location_house_city_house_gps_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listings.car')),
            ],
        ),
        migrations.CreateModel(
            name='HouseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_id', models.ForeignKey(db_column='house_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listings.house')),
            ],
        ),
    ]
