# Generated by Django 5.2 on 2025-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=100, unique=True)),
                ('total_score', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DriverRating',
            new_name='CarRating',
        ),
        migrations.DeleteModel(
            name='PassengerRating',
        ),
        migrations.RenameField(
            model_name='carrating',
            old_name='driver_id',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='carrating',
            old_name='ride_count',
            new_name='rating_count',
        ),
    ]
