# Generated by Django 5.2 on 2025-05-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rating'),
        ('rating', '0002_usercarrating_userhouserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserating',
            name='house_id',
            field=models.ForeignKey(db_column='house_id', on_delete=django.db.models.deletion.CASCADE, related_name='house_ratings', to='listings.house'),
        ),
    ]
