# Generated by Django 5.2 on 2025-05-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_rating_unique_together_rating_car_and_more'),
        ('rating', '0003_alter_houserating_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserating',
            name='house_id',
            field=models.ForeignKey(db_column='house_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating_module_ratings', to='listings.house'),
        ),
    ]
